<font color="#FF0000" face="Arial, Helvetica, sans-serif" size="4"></font>,
<font face="Verdana, Arial, Helvetica, sans-serif" size="1">(An Autonomous Institute of Govt. of Maharashtra)</font>,
<font color="#CC3300" face="Arial, Helvetica, sans-serif" size="3"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"> 19CM001</font>,
<font face="Arial, Helvetica, sans-serif" size="1"> CM5460</font>,
<font face="Arial, Helvetica, sans-serif" size="1"> COMPUTER GRAPHICS</font>,
<font face="Arial, Helvetica, sans-serif" size="2">70</font>,
<font face="Arial, Helvetica, sans-serif" size="2">69</font>,
<font face="Arial, Helvetica, sans-serif" size="2">30</font>,
<font face="Arial, Helvetica, sans-serif" size="2">29</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2">150</font>,
<font face="Arial, Helvetica, sans-serif" size="2">146</font>,
<font face="Arial, Helvetica, sans-serif" size="2">P</font>,
<font face="Arial, Helvetica, sans-serif" size="1">CM5461</font>,
<font face="Arial, Helvetica, sans-serif" size="1"> PROGRAMMING WITH PYTHON</font>,
<font face="Arial, Helvetica, sans-serif" size="2">70</font>,
<font face="Arial, Helvetica, sans-serif" size="2">69</font>,
<font face="Arial, Helvetica, sans-serif" size="2">30</font>,
<font face="Arial, Helvetica, sans-serif" size="2">29</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">23</font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2">150</font>,
<font face="Arial, Helvetica, sans-serif" size="2">145</font>,
<font face="Arial, Helvetica, sans-serif" size="2">P</font>,
<font face="Arial, Helvetica, sans-serif" size="1">CM5465</font>,
<font face="Arial, Helvetica, sans-serif" size="1">CLOUD COMPUTING</font>,
<font face="Arial, Helvetica, sans-serif" size="2">70</font>,
<font face="Arial, Helvetica, sans-serif" size="2">57</font>,
<font face="Arial, Helvetica, sans-serif" size="2">30</font>,
<font face="Arial, Helvetica, sans-serif" size="2">29</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2">150</font>,
<font face="Arial, Helvetica, sans-serif" size="2">134</font>,
<font face="Arial, Helvetica, sans-serif" size="2">P</font>,
<font face="Arial, Helvetica, sans-serif" size="1">CM5468</font>,
<font face="Arial, Helvetica, sans-serif" size="1"> PROJECT EXECUTION AND REPORT WRITING</font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2">50</font>,
<font face="Arial, Helvetica, sans-serif" size="2">49</font>,
<font face="Arial, Helvetica, sans-serif" size="2">50</font>,
<font face="Arial, Helvetica, sans-serif" size="2">49</font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2">100</font>,
<font face="Arial, Helvetica, sans-serif" size="2">98</font>,
<font face="Arial, Helvetica, sans-serif" size="2">P</font>,
<font face="Arial, Helvetica, sans-serif" size="1"> CM5474</font>,
<font face="Arial, Helvetica, sans-serif" size="1"> LINUX OPERATING SYSTEM</font>,
<font face="Arial, Helvetica, sans-serif" size="2">70</font>,
<font face="Arial, Helvetica, sans-serif" size="2">68</font>,
<font face="Arial, Helvetica, sans-serif" size="2">30</font>,
<font face="Arial, Helvetica, sans-serif" size="2">30</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2">25</font>,
<font face="Arial, Helvetica, sans-serif" size="2">24</font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2"></font>,
<font face="Arial, Helvetica, sans-serif" size="2">150</font>,
<font face="Arial, Helvetica, sans-serif" size="2">146</font>,
<font face="Arial, Helvetica, sans-serif" size="2">P</font>,
<font face="Arial, Helvetica, sans-serif" size="1">FC5490</font>,
<font face="Arial, Helvetica, sans-serif" size="1">Marklist is computerized .Please make conformation from
    theExamination Center . </font>,
<font color="#FF0000" face="Arial, Helvetica, sans-serif" size="2"></font>